### ISSUE TITLE
Work with prettier properly

### ISSUE THREAD

**Issue by lichangwei** [JSerZANP/shaku#27]
We're developing a component example site that uses prettier and shaku, where prettier users format the code and will format comments related to shaku as well, resulting in a failure to get the results we expect. Currently, we can only partially disable prettier.

enable prettier
![image](https://github.com/JSerZANP/shaku/assets/718802/6e4df554-7f61-4835-8eb2-12834cc0b74c)

disable prettier
![image](https://github.com/JSerZANP/shaku/assets/718802/98cf0035-dc5e-432b-810d-c475bec43fa9)

The whole project uses prettier, only the shaku related code snippets can't use prettier, which sucks.

I've come up with an option, but I'm not sure if it's optimal.
![image](https://github.com/JSerZANP/shaku/assets/718802/d88bfee8-4c04-4c67-a12f-d1000c6f00e6)

**Comment by JSerZANP** [comment]
Hi @lichangwei ,Thanks for trying out shaku.
This is an interesting request and I tend to think it is valid.

## 1. proposal of `<<` as position shift operator

Actually when I first created Shaku, I had the idea of using `<<` as position shift operator to allow underlining from the first character in a line - obviously we need `//` for the comment which means we cannot target the first two chars.

as-is
```
function a() {
//^
//[This is a function]
}
```

to-be
```
function a() {
//^<<
//[This is a function]<<
}
```

But it was not implemented for its low priority,  maybe I can just pick it up. 🤔 

## 2. Prettier plugin to ignore Shaku lines?

Shaku is supposed to be used in markdown(or if you are using it in different context?), so mainly it should be used to explain code. 

Maybe we can create Prettier plugin but it seems to be tricky because Shaku lines has to be aligned with actually code lines in the context. 

I'm not familiar with how Prettier works under the hood, need more time here.

**Comment by lichangwei** [comment]
Yeah, `<` is a good idea, programmers understand it at a glance.

In our case, we created a React component library in-house and maintain component example sites. Sorry it's not open source, so there's no link to show you. We have written a large number of sample code files in the sample site, which shows how the sample code renders and what code was used. So I took a tsx file and read it, put it into \`\`\`tsx ${code} \`\`\` to make it into MD format, and then used shaku to render the code style.

![image](https://github.com/JSerZANP/shaku/assets/718802/75f98bf2-fd4b-445e-a10e-38f8c7270ced)

**Comment by JSerZANP** [comment]
@lichangwei 
It looks awesome! ! 
I'll support  `<` as soon as possible

**Comment by lichangwei** [comment]
Awesome, you saved my code. Thank you very very very much.

**Comment by JSerZANP** [comment]
@lichangwei  seems like I didn't publish the right package. please use latest version(`0.1.3`) which also includes performance improvements
